#undef USE_BME280
#define USE_BME280 1
#undef USE_BATTERY
#define USE_BATTERY 1
#undef USE_WIND_SPEED
#define USE_WIND_SPEED 1
#undef USE_WIND_DIR
#define USE_WIND_DIR 1
#undef USE_RAIN
#define USE_RAIN 1
#undef LOG_INTERVAL_MS
#define LOG_INTERVAL_MS 10000UL
#undef CONFIG_PRESET_ID
#define CONFIG_PRESET_ID "WEATHER_BME280_WIND_RAIN_BAT"
